name: _iwu_pack_network
description: _iwu_pack_network project.
version: 0.0.2

environment:
  sdk: ">=2.19.4 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ">=4.0.2"
  dio: ">=5.3.1"
  pretty_dio_logger: ^1.3.1
  mqtt_client: ">=10.0.0"
  
  # _iwu_pack: ">=0.0.3"
  _iwu_pack: 
    path: ../core

dev_dependencies:
  flutter_lints: ">=2.0.3"

jsonToDart: 
  typeChecking: false
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false
  mergeArrayApproach: false #default: true
